/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-KeweenawMap--SHNWfdx2r6OS2jzPDiepEUBkbeYRols",
  "version": "2020-11-20"
}

export default ebconfig;